test:
  path: /test
  controller: App\Controller\ApiCitiesPlacesController::test

getCitiesFrom3rdPartyApiAndSaveToDB:
  path: /cities/places/savedb
  controller: App\Controller\ApiCitiesPlacesController::saveCitiesPlacesToDB